name: Lint

on: [push]

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [18]

        steps:
            - name: Setup node env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              run: npm ci

            - name: Run lint
              run: npm run style:all
