name: Lint

on:
    pull_request:
        types: [opened, edited, reopened, synchronize]

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Setup node env
              uses: actions/setup-node@v4
              with:
                  node-version: 21

            - name: Install dependencies
              run: npm ci
                #   if [ -e package-lock.json ]; then
                #   npm ci
                #   else
                #   npm i
                #   fi

            - name: Run lint
              run: npm run style:all
